name: Deploy to Hugging Face Space

on:
  push:
    branches: [ "hugging_space" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.email "aancanic77@yahoo.com"
          git config --global user.name "aancanic77"

      - name: Clone Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF }}
        run: |
          git clone https://huggingface.co/spaces/aancanic77/dashboard04 hfspace
          cp -r * hfspace/ || true
          cd hfspace
          git add .
          git commit -m "Auto deploy from GitHub" || true
          git push https://$HF_TOKEN@huggingface.co/spaces/aancanic77/dashboard04
