name: Deploy to Hugging Face Space

on:
  push:
    branches: [ "main", "hugging_space" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug secret
        env:
          HF_TOKEN: ${{ secrets.HF }}
        run: |
          if [ -z "$HF_TOKEN" ]; then
            echo "TOKEN ESTE GOL"
          else
            echo "TOKEN ESTE PREZENT"
          fi

      - name: Clone Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF }}
        run: |
          rm -rf hfspace
          git clone https://huggingface.co/spaces/aancanic77/dashboard04.git hfspace

          rsync -av --exclude=hfspace --exclude=.git ./ hfspace/

          cd hfspace
          git config user.email "anca.atodiresei@gmail.com"
          git config user.name "aancanic77"

          git add .
          git commit -m "Auto deploy from GitHub" || true
          git push https://$HF_TOKEN@huggingface.co/spaces/aancanic77/dashboard04.git

